### ISSUE TITLE
Compiling blink example fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by MarkuBu** [avr-rust/book.avr-rust.com#29] opened 2020-10-27 18:45 UTC
I followed the instructions in th book, but I can't compile the blink example 

```
error: could not compile `core`

Caused by:
  process didn't exit successfully: `rustc 
  --crate-name core 
  --edition=2018 /home/markus/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/lib.rs 
  --error-format=json 
  --json=diagnostic-rendered-ansi,artifacts 
  --crate-type lib 
  --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no -C metadata=765ea16169eccad7 -C extra-filename=-765ea16169eccad7 
  --out-dir /home/markus/dev/rust-avr/blink/target/avr-atmega328p/release/deps 
  --target /home/markus/dev/rust-avr/blink/avr-atmega328p.json -Z force-unstable-if-unmarked -L dependency=/home/markus/dev/rust-avr/blink/target/avr-atmega328p/release/deps -L dependency=/home/markus/dev/rust-avr/blink/target/release/deps 
  --cap-lints allow` (signal: 11, SIGSEGV: invalid memory reference)
```

**Comment by dylanmckay** [comment] 2020-10-29 13:07
Duplicate of https://github.com/rust-lang/rust/issues/76930

I'm going to close this but thanks for raising!

**Closed by dylanmckay** 2020-10-29 13:07 UTC
